### ISSUE TITLE
Run `prettier` on pre-commit

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/react-query-tool#11]

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.1.0) :rocket:

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.1.0) :rocket:
