### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/react-query-tool#14]
- [x] Alerts
  - [x] Navbar
  - [x] Logo
  - [x] favicon
  - [x] Form validation
  - ~[ ] name ellipses~ No need for ellipses expansion and tooltip since dataset names seems to be wrapping around nicely
  - [x] summary stats
  - [x] toasts
  - [x] Button loading
  - [x] non-white background color of the tool group buttons on hover

**Comment by surchs** [comment]
:rocket: Issue was released in [`v0.1.0`](https://github.com/neurobagel/query-tool/releases/tag/v0.1.0) :rocket:
