### ISSUE TITLE
Set up CIs

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/react-query-tool#27]
- [x] #46
- [x] #41 
- ~[ ] #48~

**Comment by Sauradip07** [comment]
@rmanaem 
Ensure that CodeQL setup is correctly configured to discover vulnerabilities across the codebase. Additionally, enforce code quality practices using ESLint and other scripts to maintain a high standard of code cleanliness and security.

Checklist:

- [x] Verify that ESLint is configured to disable checks recursively on TypeScript files within the 'src' directory and its subdirectories.

- [x]  Confirm that the Line Count script is set up to analyze the 'lib' and 'src' directories to identify files exceeding a predetermined line count threshold.

- [x] Ensure that the Count Changes File script is implemented to analyze pull requests and detect if the count of changed files exceeds the defined limit of 20.

- [x] Check for unauthorized changes to sensitive files and branches, including but not limited to '.github/**', 'env.example', '.node-version',  package.json' , 'tsconfig.json' ,'.gitignore' ,'.eslintrc.json','.eslintignore ' ,'vite.config.ts' etc.

- [x] Set up Code-Quality-Checks, which includes linting, formatting, and type-checking processes to maintain code quality standards.

**Details:**

- **Line Count Script**: Analyses codebase for files exceeding a predefined line count limit, encouraging contributors to create concise and maintainable code.
- **Count Changes File Script**: Monitors pull requests to prevent unintentional merges and ensure adherence to project practices.
- **Sensitive Files and Branch Check**: Guard against unauthorized changes to critical files and branches to maintain security and stability.
- **Code-Quality-Checks**: Enforces linting, formatting, and type-checking to uphold code quality practices.


 Please check the PR #45

**Comment by surchs** [comment]
@rmanaem I think we should also add the repo here: https://github.com/neurobagel/workflows/blob/0ec6c96a36929fb762e86c6ea96b40c8860d58fb/.github/sync.yml,

probably under 
- project automation
- auto-release

and then also add a specific workflow for the docker build and push. wdyt? @alyssadai does that look good to you as a plan?

**Comment by alyssadai** [comment]
That makes sense to me.

> and then also add a specific workflow for the docker build and push

To clarify, I think all that would be needed here is another section under `sync.yml` for the react-query-tool that looks like this https://github.com/neurobagel/workflows/blob/0ec6c96a36929fb762e86c6ea96b40c8860d58fb/.github/sync.yml#L60-L68, with the `docker_repo_name` field updated.

**Comment by rmanaem** [comment]
Since #48 no longer requires adding a docker CI, it'll be no longer tracked by this issue and therefore we can close this issue.
